name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
    - name: Checkout Repository
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
    - name: Set up Java
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3
      with:
        java-version: "17"
        distribution: "temurin"
        cache: "maven"
    - name: Test
      run: mvn clean verify
